##################################
mortality_prediction:
  gru:

  transformer:

  deepr:

  adacare:

  stagenet:

  grasp:

  graphcare:

##################################
readmission_prediction:
  gru:

  transformer:

  deepr:

  adacare:

  stagenet:

  grasp:

  graphcare:

##################################
los_prediction:
  gru:
    lr: 0.0001
    input_dim: 128
    hidden_dim: 128
    layers: 2

  transformer:
    lr: 0.00001
    input_dim: 64
    ff_dim: 64
    head_num: 2
    encoder_depth: 2
    decoder_depth: 2

  deepr:
    lr: 0.0001
    start_embed_dim: 128
    hidden_dim: 128
    window_size: 3

  adacare:
    input_dim: 64
    hidden_dim: 64
    kernel_size: 2
    kernel_num: 64
    r_v: 4
    r_c: 4
    activation: sigmoid

  stagenet:
    lr: 0.0001
    inpu_dim: 128
    hidden_dim: 128
    conv_size: 4
    level: 2

  grasp:
    lr: 0.0005
    start_embed_dim: 64
    cluster_num: 12
    hidden_dim: 64
    block: ConCare

  graphcare:
    lr: 0.0001
    start_embed_dim: 128
    hidden_dim: 128
    gnn: BAT
    gnn_layer: 3
    decay_rate: 0.01
    patient_mode: joint
    use_alpha: True
    use_beta: True
    edge_attn: True
    attn_init: 1
    dropout: 0.5

##################################
drug_recommendation:
  gru:
    lr: 0.001
    input_dim: 128
    hidden_dim: 128
    layers: 1

  transformer:

  deepr:
    lr: 0.001
    max_weeks_between: 630
    start_embed_dim: 128
    hidden_dim: 128
    window_size: 3

  adacare:

  stagenet:
    lr: 0.0001
    inpu_dim: 128
    hidden_dim: 128
    conv_size: 2
    level: 1

  grasp:

  graphcare:

##################################
phenotype_prediction:
  gru:

  transformer:

  deepr:

  adacare:

  stagenet:

  grasp:

  graphcare:
