dataset: mimiciv
task: readmission_prediction
seed: 0

age_thresh_low: 18
age_thresh_high: 80
code_freq_filter: 60
visit_thresh: 15
pad_dim: 60

train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
train_batch_size: 3
val_batch_size: 3
test_batch_size: 3
num_epochs: 100
val_freq: 5
logging_freq: 200

triplet_method: co-occurrence

model:
  name: AdaCare
  model_type: baseline
  args:
    input_dim: 128
    hidden_dim: 128
    kernel_size: 2
    kernel_num: 64
    r_v: 4
    r_c: 4
    activation: sigmoid

optimizer:
  name: Adam
  args:
    lr: 0.0005
    weight_decay: 0.0001

scheduler:
  name: StepLR
  args:
    step_size: 20
    gamma: 0.0001

criterion:
  binary_entropy:
    reduction: mean

metrics:
  - AUROC
  - AUPRC
  - AP

raw_data_path: /home/engs2635/Desktop/caizi/raw_data
save_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
graph_construction_path: /home/engs2635/Desktop/caizi/graph_construction
log_path: /home/engs2635/Desktop/caizi/CHI/logs
