dataset: mimiciv
task: pretrain
seed: 0
save_params: True

triplet_method: LLM
code_thresh: 60
visit_thresh: 15

train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
max_epoch: 120
val_freq: 1
logging_freq: 50

model:
  name: MPCare_Pretrain
  model_type: base
  mode: train
  freeze: False
  save_embed: True
  load_embed:
  args:
    start_embed_dim: 64
    gnn_type: CompGCN
    gnn_layer: 1
    hidden_dim: 64
    head_num: 2
    depth: 2
    set_trans_out_num: 1
    max_weeks_between: 630

optimizer:
  name: Adam
  args:
    lr: 0.0005
    weight_decay: 0.

scheduler:

criterion:
  contrastive:
    temperature: 0.1
    factor: 1
  binary_entropy:
    reduction: mean

metrics:
  - AUROC
  - AUPRC
  - F1
  - Jaccard
  - Accuracy

processed_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
log_path: /home/engs2635/Desktop/caizi/CHI/logs
pretrained:
