dataset: mimiciv
task: mortality_prediction
seed: 0

# Data Processing
age_thresh_low: 18
age_thresh_high: 80
code_freq_filter: 60
visit_thresh: 15
pad_dim: 60

# Training Setting
train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
batch_size: 3
num_epochs: 50
val_freq: 5

# KG Configurations
triplet_method: co-occurrence

# Model Configurations
prototype_num: 5
embed_dim: 8
gnn_layer: 3
gnn_hidden_dim: 128
set_num_heads: 2
set_encoder_depth: 2
set_decoder_depth: 2
set_trans_hidden_dim: 128
set_trans_out_dim: 128

optimizer: Adam
lr: 0.00001
weight_decay: 0.00001

# Paths
raw_data_path: /home/engs2635/Desktop/caizi/raw_data
save_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
graph_construction_path: /home/engs2635/Desktop/caizi/graph_construction
log_dir: /home/engs2635/Desktop/caizi/CHI/logs
