dataset: mimiciv
task: mortality_prediction
seed: 0

# Training Setting
train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
batch_size: 3
num_epochs: 50
val_freq: 5

# KG Configurations
triplet_method: co-occurrence

# Model Configurations
embed_dim: 8
gnn_layer: 3
gnn_hidden_dim: 128
trans_hidden_dim: 128

# Paths
raw_data_path: /home/engs2635/Desktop/caizi/raw_data
save_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
graph_construction_path: /home/engs2635/Desktop/caizi/graph_construction
