dataset: mimiciv
task: mortality_prediction
seed: 0

age_thresh_low: 18
age_thresh_high: 80
code_freq_filter: 60
visit_thresh: 15
pad_dim: 60

train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
train_batch_size: 3
val_batch_size: 3
test_batch_size: 3
num_epochs: 100
val_freq: 5
logging_freq: 200
triplet_method: co-occurrence

model:
  name: OurModel
  model_type: base
  args:
    start_embed_dim: 128
    gnn_layer: 1
    gnn_hidden_dim: 128

    set_head_num: 2
    set_encoder_depth: 1
    set_decoder_depth: 1
    set_trans_hidden_dim: 128
    set_trans_out_dim: 128
    set_trans_out_num: 1

    proto_num: 16
    proto_head_num: 4
    proto_depth: 1
    proto_hidden_dim: 128
    proto_out_dim: 128

    max_weeks_between: 630
    time_head_num: 4
    time_depth: 1
    time_trans_hidden_dim: 128

optimizer:
  name: Adam
  args:
    lr: 0.00001
    weight_decay: 0.00001

scheduler:
  # name: StepLR
  # args:
  #   step_size: 10
  #   gamma: 0.00001

criterion:
  contrastive:
    margin: 10
  binary_entropy:
    reduction: mean
  # focal:
  #   alpha: 0.2
  #   gamma: 2

metrics:
  - AUROC
  - AUPRC
  - AP

raw_data_path: /home/engs2635/Desktop/caizi/raw_data
save_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
graph_construction_path: /home/engs2635/Desktop/caizi/graph_construction
log_path: /home/engs2635/Desktop/caizi/CHI/logs
