dataset: mimiciv
task: mortality_prediction
seed: 0

triplet_method: co-occurrence
code_thresh: 60
visit_thresh: 15

train_proportion: 0.8
val_proportion: 0.1
test_proportion: 0.1
train_batch_size: 3
val_batch_size: 3
test_batch_size: 3
num_epochs: 100
val_freq: 5
logging_freq: 200

model:
  name: GraphCare
  model_type: baseline
  args:
    start_embed_dim: 128
    hidden_dim: 128
    gnn: BAT
    gnn_layer: 1
    decay_rate: 0.01
    patient_mode: joint
    use_alpha: True
    use_beta: True
    edge_attn: True
    

optimizer:
  name: Adam
  args:
    lr: 0.00001
    weight_decay: 0.00001

scheduler:
  # name: StepLR
  # args:
  #   step_size: 10
  #   gamma: 0.00001

criterion:
  binary_entropy:
    reduction: mean

metrics:
  - AUROC
  - AUPRC
  - AP

raw_data_path: /home/engs2635/Desktop/caizi/raw_data
processed_data_path: /home/engs2635/Desktop/caizi/CHI/data/mimiciv
log_path: /home/engs2635/Desktop/caizi/CHI/logs
